package godebug

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"reflect"
	"runtime"
	"strings"
	"sync/atomic"

	"github.com/jtolds/gls"
)

// Scope represents a lexical scope for variable bindings.
type Scope struct {
	vars   map[string]interface{}
	parent *Scope
}

var scopeStack []*Scope

// EnteringNewScope returns a new Scope and internally sets
// the current scope to be the returned scope.
func EnteringNewScope() *Scope {
	s := &Scope{vars: make(map[string]interface{})}
	scopeStack = append(scopeStack, s)
	return s
}

// EnteringNewChildScope returns a new Scope that is the
// child of s and internally sets the current scope to be
// the returned scope.
func (s *Scope) EnteringNewChildScope() *Scope {
	child := &Scope{
		vars:   make(map[string]interface{}),
		parent: s,
	}
	scopeStack = append(scopeStack, child)
	return child
}

// End informs the debugger that the program is moving outside
// the text of s, and thus the bindings in s are no longer valid.
func (s *Scope) End() {
	scopeStack = scopeStack[:len(scopeStack)-1]
}

// Declare creates new variable bindings in s from a list of name, value pairs.
// The values should be pointers to the values in the program rather than copies
// of them so that s can track changes to them.
func (s *Scope) Declare(namevalue ...interface{}) {
	var i int
	for i = 0; i+1 < len(namevalue); i += 2 {
		name, ok := namevalue[i].(string)
		if !ok {
			panic("programming error: got odd-numbered argument to RecordVars that was not a string")
		}
		s.vars[name] = namevalue[i+1]
	}
	if i != len(namevalue) {
		panic("programming error: called RecordVars with odd number of arguments")
	}
}

const (
	run int32 = iota
	next
	step
)

var (
	currentState     int32
	currentDepth     int
	debuggerDepth    int
	context          = getPreferredContextManager()
	goroutineKey     = gls.GenSym()
	goroutineID      = gls.GenSym()
	currentGoroutine int32
	ids              idPool
)

// EnterFunc marks the beginning of a function. Calling fn should be equivalent to running
// the function that is being entered. If proceed is false, EnterFunc did in fact call
// fn, and so the caller of EnterFunc should return immediately rather than proceed to
// duplicate the effects of fn.
func EnterFunc(fn func()) (proceed bool) {
	// If we're in state run, just keep going.
	if atomic.LoadInt32(&currentState) == run {
		return true
	}

	// We've entered a new function. If we're in step or next mode we have some bookkeeping to do,
	// but only if the current goroutine is the one the debugger is following. How do we determine
	// that? With goroutine local storage. In particular, with the github.com/jtolds/gls API.
	//
	// We consult context to determine whether we are the goroutine the debugger is following. If
	// context has not seen our goroutine before, the ok it returns is false. Why would that happen?
	// godebug supports generating debug code for a library that is later built into a binary. If that
	// happens, then context will not see any goroutines until they call code from the debugged library.
	val, ok := context.GetValue(goroutineKey)
	if !ok {
		// This is the first time context has seen the current goroutine.
		//
		// Or, more accurately and precisely: This is the first frame in the current stack that contains
		// code that has been generated by godebug.
		//
		// We record some bookkeeping information with context and then continue running. This means we will
		// invoke fn, which means the caller should not proceed. After running it, return false.
		id := ids.Acquire()
		defer ids.Release(id)
		context.SetValues(gls.Values{goroutineID: id}, fn)
		return false
	}
	if val.(int32) == atomic.LoadInt32(&currentGoroutine) {
		currentDepth++
	}
	return true
}

// ExitFunc marks the end of a function.
func ExitFunc() {
	if atomic.LoadInt32(&currentState) == run {
		return
	}
	val, ok := context.GetValue(goroutineKey)
	if !ok {
		panic("Logic error in the debugger. Sorry! Let me know about this in the github issue tracker.")
	}
	if val.(int32) != atomic.LoadInt32(&currentGoroutine) {
		return
	}
	if currentState == next && currentDepth == debuggerDepth {
		debuggerDepth--
	}
	currentDepth--
}

// Line marks a normal line where the debugger might pause.
func Line() {
	if currentState == run || (currentState == next && currentDepth != debuggerDepth) {
		return
	}
	debuggerDepth = currentDepth
	printLine()
	waitForInput()
}

var skipNextElseIfExpr bool

// ElseIfSimpleStmt marks a simple statement preceding an "else if" expression.
func ElseIfSimpleStmt(line string) {
	SLine(line)
	if currentState == next {
		skipNextElseIfExpr = true
	}
}

// ElseIfExpr marks an "else if" expression.
func ElseIfExpr(line string) {
	if skipNextElseIfExpr {
		skipNextElseIfExpr = false
		return
	}
	SLine(line)
}

// SLine is like Line, except that the debugger should print the provided line rather than
// reading the next line from the source code.
func SLine(line string) {
	if currentState == run || (currentState == next && currentDepth != debuggerDepth) {
		return
	}
	debuggerDepth = currentDepth
	fmt.Println("->", line)
	waitForInput()
}

// SetTrace is the entrypoint to the debugger.
func SetTrace() {
	currentState = step
}

var input *bufio.Scanner

func init() {
	input = bufio.NewScanner(os.Stdin)
}

func getVar(name string) (i interface{}, ok bool) {
	scope := scopeStack[len(scopeStack)-1]
	for scope != nil {
		if i, ok = scope.vars[name]; ok {
			return i, true
		}
		scope = scope.parent
	}
	return nil, false
}

func waitForInput() {
	for {
		fmt.Print("(godebug) ")
		if !input.Scan() {
			fmt.Println("quitting session")
			currentState = run
			return
		}
		s := input.Text()
		switch s {
		case "n", "next":
			currentState = next
			return
		case "s", "step":
			currentState = step
			return
		}
		if v, ok := getVar(strings.TrimSpace(s)); ok {
			fmt.Println(dereference(v))
			continue
		}
		var cmd, name string
		n, _ := fmt.Sscan(s, &cmd, &name)
		if n == 2 && (cmd == "p" || cmd == "print") {
			if v, ok := getVar(strings.TrimSpace(name)); ok {
				fmt.Println(dereference(v))
				continue
			}
		}
		fmt.Printf("Command not recognized, sorry! You typed: %q\n", s)
	}
}

func dereference(i interface{}) interface{} {
	return reflect.ValueOf(i).Elem().Interface()
}

func printLine() {
	_, file, line, ok := runtime.Caller(2)
	if !ok {
		fmt.Println("Hmm, something is broken. Failed to identify current source line.")
		return
	}
	printLineFromFile(line, file)
}

var parsedFiles map[string][]string

func init() {
	parsedFiles = make(map[string][]string)
}

func printLineFromFile(line int, file string) {
	f, ok := parsedFiles[file]
	if !ok {
		f = parseFile(file)
		parsedFiles[file] = f
	}
	if line >= len(f) {
		fmt.Printf("Hmm, something is broken. Current source line = %v, current file = %v, length of file = %v\n", line, file, len(f))
		return
	}
	fmt.Println("->", f[line])
}

func parseFile(file string) []string {
	f, err := os.Open(file)
	if err != nil {
		fmt.Println("Failed to open current source file:", err)
		return nil
	}
	var lines []string
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		lines = append(lines, string(bytes.TrimSpace(scanner.Bytes())))
	}
	if err = scanner.Err(); err != nil {
		fmt.Println("Error reading current source file:", err)
	}
	return lines
}
